### ISSUE TITLE
Different cacheing behaviour then the expected from getStaticProps function

### ISSUE THREAD

**Issue by abhi09882** [jthegedus/firebase-gcp-examples#104]
## Which Package & Your Environment

* Package in this repo: https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs
* OS: macOS Catalina 
* Node Version: 10
* Pkg Manager: yarn
* Shell: bash
* Browser & version: Chrome Version 81.0.*
* Language: Javascript

## Expected Behaviour

I am expecting to have the same behavior in the browser as mentioned in code. `immutable`
https://github.com/jthegedus/firebase-gcp-examples/blob/master/functions-nextjs/pages/blog/%5Bpid%5D.js

![image](https://user-images.githubusercontent.com/17054925/82730543-f3fc7680-9d43-11ea-9d16-cb34f3663738.png)

## Actual Behaviour

But, getting this header in response `stale-while-revalidate`
Due to which firebase CDN is not always caching this page. ([pid].js) and some times I am getting cache MISS.

![image](https://user-images.githubusercontent.com/17054925/82730592-3b830280-9d44-11ea-9012-de20f124468c.png)

initially (just after deployment) not even getting cache headers.
![image](https://user-images.githubusercontent.com/17054925/82731791-8143c900-9d4c-11ea-9bac-6713ea61ffe8.png)

## Possible Solution

Probably a correct response header through server.js file. 

## Context

I have a requirement where my app will have 40k pages and all of them gonna change on the next build. I want to cache all my pages at the CDN level until the next build.

I tried setting a response header in `getServerSideProps`. it works fine for me. But, my question is can I achieve this with `getStaticProps`.
![image](https://user-images.githubusercontent.com/17054925/82730707-2064c280-9d45-11ea-8364-bf86c226b76b.png)

**Comment by rshemant** [comment]
@jthegedus 
one thing I noticed when deployed to vercel its showing parcel cached result. which is good. I can see there is no CDN at the vercel level. but ser caching is doing his job.

https://nextjs-vercel-three.now.sh/blog/U4brLmzUTZv7Qlr6frlS

![image](https://user-images.githubusercontent.com/49910052/82744128-b89b8f80-9db7-11ea-9365-441174f2df20.png)

**Comment by jthegedus** [comment]
@abhi09882 good catch, this was an error by me. It is not `immutable` but `stale-while-revalidate`. All `getStaticProps` with `fallback:true` pages have their cache-controls set here - https://github.com/zeit/next.js/blob/canary/packages/next/next-server/server/send-payload.ts

```
res.setHeader('Cache-Control',s-maxage=31536000, stale-while-revalidate`)
```

With `s-maxage` being set the Firebase CDN should cache this page for 1 year. `stale-while-revalidate` then forces a refresh of these values. Obviously this is not ideal, and we would want to remove the `stale-while-revalidate` value. I am unsure how this would be done without editing the `send-payload.ts` file.

My recommendation would be to just use SSR and set the cache-controls you require for those specific server routes. The more I am using Next.js SSG the more I am finding it is only going to work optimally on the Vercel platform.

@rshemant Any deployment to Vercel will be different as that platform is optimized for Next.js by reading the build manifest and ssg manifests which are output on build. Vercel performs the CDN caching internally which is why you have the cache-controls with `max-age=0` and `must-revalidate` for an SSG page (assuming you're using this sample code).

**Comment by jthegedus** [comment]
It is issues like these that I am still uncovering that have stopped me writing the blog post for this example. There's a lot to go through.

**Comment by jthegedus** [comment]
@abhi09882 I would recommend watching this whole video, it is very informative - https://youtu.be/7_2CJs_VZk4

**Comment by rshemant** [comment]
@jthegedus  Thanks for awesome comments.

**Comment by jthegedus** [comment]
@abhi09882 Since this was an error in the comments by me, I have corrected them and so will close this issue. SSR is my recommendation as you can set the cache control without `stale-while-revalidate`

**Comment by rshemant** [comment]
> @abhi09882 I would recommend watching this whole video, it is very informative on Firebase Hosting and cache flushing strategies - https://youtu.be/7_2CJs_VZk4

as you suggested this video can I please ask a few questions.

1. In the video Michael as suggested to store generated pages to *cloud store* can I use this approach and store nextjs generated pages to *google cloud store* same way. If yes, could you please suggest how can I do that with nextjs.

1. he suggested the purge method to clean CDN level coaching. 
example - `curl -X PURGE https://fir-test-2ec0d.web.app/blog`. 
It looks like this is not so safe because anyone can do that from the open internet. of course, it's not a big deal even if someone clears the CDN for us as files are stored in cloud storage only. what's your take on this.

Michael suggested AMP optimization. here Next js [AMP module](https://nextjs.org/docs/api-reference/next/amp) will help me for sure.

**Comment by jthegedus** [comment]
>as you suggested this video can I please ask a few questions.

yes

>store generated pages to cloud store can I use this approach and store nextjs generated pages to google cloud store same way

It can be done with a custom server and push the Next.js `res` output to Cloud Storage. As I pointed out earlier, Next.js uses an in-memory cache to store realtime generated pages https://github.com/zeit/next.js/blob/canary/packages/next/next-server/server/spr-cache.ts . I have asked if they could support an API where we can provide a function to store the cache in blob storage like GCS/S3 instead of in-memory as Cloud Functions and Cloud Run etc are ephemeral compute and don't have long-lived storage like I believe Vercel does.

>It looks like this is not so safe because anyone can do that from the open internet

I believe the CDN purge must come from an authenticated source, and Cloud Functions in your project have default credentials to call protected APIs (I have not tested this, but believe this to be the case because Google has made the tool and this makes sense).
Here is Michael's example code used to perform the purge in a Cloud Function: https://github.com/mbleigh/escapable-amp/blob/72e2e234d64d595461fd0bf3ed16270e203935b1/functions/src/materialize.ts#L24

**Comment by jthegedus** [comment]
Here is the [Google Group feature request for proper CDN flush support](https://groups.google.com/forum/#!topic/firebase-talk/_q9qM82QV6U) as the code in that repo is not officially supported.

**Comment by jthegedus** [comment]
I should point out that the only reason `stale-while-revalidate` is not ideal here is because each page request hit's our Cloud Function. This isn't a bug per se, but with static content we know isn't going to change, not ideal as we're paying for Cloud Function requests.

I just pushed a Cloud Run + Next.js example which has better cost and cold-start than Cloud Functions because each instance can handle multiple requests.

**Comment by rshemant** [comment]
@jthegedus 
Hey James, Thanks for sharing 'cloud run' example.
I am getting below error while setup. could you please suggest anything here.

![image](https://user-images.githubusercontent.com/49910052/82756021-c46c6d80-9e1a-11ea-8ca8-17e24225150f.png)

**Comment by jthegedus** [comment]
Did your Cloud Run deployment succeed? If so, make sure the region you deployed your Cloud Run service matches the region in your `firebase.json`.

It might also just be that you need to upgrade to Blaze payment model for your Firebase project.

**Comment by jthegedus** [comment]
@rshemant The idea you had for storing files on GCS is essentially what https://github.com/danielcondemarin/serverless-next.js does but on AWS.

**Comment by rshemant** [comment]
@jthegedus 
Mate, pardon me if I am wrong. I found even all the static resource requests are served by function.

https://github.com/jthegedus/firebase-gcp-examples/blob/d0728457e2dc269139a80f55a7236c838aecd175/functions-nextjs/firebase.json#L28

as we are not leveraging **Firebase** hosting capabilities, even to serve static resources the function sleep time is causing huge difference in performance

**Comment by jthegedus** [comment]
In the "need to know" section of the readme I link to [Firebase Hosting priority order](https://firebase.google.com/docs/hosting/full-config#hosting_priority_order)

This is a feature of Firebase Hosting that describes the order in which a request is fulfilled:

>The different Firebase Hosting configuration options described on this page can sometimes overlap. If there is a conflict, Hosting determines its response using the following priority order:
>1. Reserved namespaces that begin with a /__/* path segment
>2. Configured redirects
>3. Exact-match static content
>4. Configured rewrites
>5. Custom 404 page
>6. Default 404 page

Note that exact content (3) is matched if possible, before rewriting (4) to the function.

All files that get pushed to Firebase Hosting will be served from Firebase Hosting before hitting the Cloud Function.

iSSG pages used in `/blog/[pid].js` are different because of how iSSG works. We have the `fallback:true` set so we can generate new pages after deployment. SSG pages have Cache-Controls set with:

```
'Cache-Control',s-maxage=31536000, stale-while-revalidate
```

These pages are CDN cached (because of the s-maxage header telling the CDN how long to cache for) and served if they exist from the CDN, then `stale-while-revalidate` sends a request to our Next.js server on our Cloud Function to refresh the generated page contents. This is ideal from a user perspective as they see content from CDN, then it gets updated in the background from the Cloud Function. It is not ideal for cost as it means each request will hit our Cloud Function like SSR. 

**iSSG is not a cost optimisation, but an experience optimisation.**

I hope this clears up some areas. I tried to cover everything in the readme, so have a click on all the links to read more

**Comment by rshemant** [comment]
Great answer @jthegedus , I really got a good idea about the firebase hosting structure.

One thing I would like to ask about the next js.

![image](https://user-images.githubusercontent.com/49910052/83249534-0fef9480-a1ea-11ea-8d22-6fb59e7bc531.png)

There is a tag called `__NEXT_DATA__` in my SSG app. that contains whole prop data of my page.
this is making page size big and opening an easy window for web scrapping.

What you reckon how could I stop this to happen.

**Comment by jthegedus** [comment]
I do not have a complete understanding of this functionality, but I believe `__NEXT_DATA__` is the mechanism Next.js uses to hydrate the data for the page from the `.json` which is different for each SSG page. I do not think this can be replaced. Perhaps you should ask this question in the Next.js repo as you will have better feedback about what you may be able to do to stop web scraping.
