### ISSUE TITLE
Some functions-nextjs questions

### ISSUE THREAD

**Issue by mrmartineau** [jthegedus/firebase-gcp-examples#158]
This is more of a question so would be better suited to Github discussions.. 

## Which Package & Your Environment

* Package in this repo: functions-nextjs
* OS: Mac
* Node Version: v14.13.1
* Pkg Manager: yarn
* Shell: fish
* Browser & version: Vivaldi latest
* Language: English

## Questions

1. Can you explain the usage of `sprFlushToDisk` in this example? Why is it needed? After a little digging, it is disabling [serverless pre rendering](https://vercel.com/blog/serverless-pre-rendering), is that correct? but why?
2. How are you managing environment variables that are used both in the Next app and by a Cloud function (like Next's API routes)? I am using [next-firebase-auth](https://github.com/gladly-team/next-firebase-auth) which uses env vars heavily, see this [example file](https://github.com/gladly-team/next-firebase-auth/blob/main/example/utils/initAuth.js). I do not see how they can be shared, but that might be a misunderstanding on my part.
3. In the readme, you recommend not using SSR for firebase authentication. Can you elaborate? As I mentioned above, I am using next-firebase-auth to handle my auth. I am wondering if it was a mistake.
4. I am having issues deploying my app to Firebase. It does not deploy the latest code up. I think it must be a configuration issue, but I'm wondering if you have experienced that before.

My config is:

```json
{
  "hosting": [
    {
      "public": "nextjs",
      "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
      "cleanUrls": true,
      "rewrites": [
        {
          "source": "**",
          "function": "nextServer"
        }
      ],
      "target": "staging",
      "predeploy": "yarn build"
    },
    {
      "public": "storybook-static",
      "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
      "cleanUrls": true,
      "target": "storybook",
      "predeploy": "yarn storybook:build"
    }
  ],
  "functions": {
    "source": ".",
    "runtime": "nodejs12",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**",
      "firebase-debug.log",
      "src/components/**",
      "src/hooks/**",
      "src/pages/**",
      "src/theme/**",
      "src/types/**",
      "src/utils/**",
      "public/**",
      "firestore.rules",
      "readme.md"
    ],
    "predeploy": "yarn build"
  }
}
```

I added `predeploy` steps today because that seemed to fix my deployment issues temporarily, but they are back now for some reason.

Also, I set `public` to `nextjs` instead of what you have in your example (`public/`). It doesn't seem to make a difference, can you confirm why?

Thanks in advance. I am well aware that you are not customer support, but your example is the most thorough that I have found.

**Comment by jthegedus** [comment]
Hi mate, sorry it took so long to get back to you. Slammed at work atm. Take my answers with a grain of salt because I may have forgotten the finer details.

>Can you explain the usage of sprFlushToDisk in this example? Why is it needed? After a little digging, it is disabling serverless pre rendering, is that correct? but why?

`sprFlushToDisk` tries to write to the disk. I was getting a warning with Cloud Functions because CF do not have writable disk space where Next.js tries to write, so I disabled this feature.

I am not sure Serverless Pre-rendering as a feature is any different to [GetStaticProps Incremental Static Generation with revalidate set to 1][1]

>How are you managing environment variables that are used both in the Next app and by a Cloud function (like Next's API routes)? I am using next-firebase-auth which uses env vars heavily, see this example file. I do not see how they can be shared, but that might be a misunderstanding on my part.

According to the [docs][2], Next.js injects env vars into `process.env`, so I would expect that to still work, regardless that the Node runtime is a Cloud Function. It is Next.js that shares env vars between **its** client and server. Since Next.js endpoints are executed in the server environment of the Next.js framework it should have access to it's env vars. Whether Cloud Function defined env vars take precendent over Next.js defined env vars I do not know.

>In the readme, you recommend not using SSR for firebase authentication. Can you elaborate? As I mentioned above, I am using next-firebase-auth to handle my auth. I am wondering if it was a mistake.

I personally recommend against using SSR for authenticated routes. This is because data fetched on the server is not protected by Firestore security rules, caching of sensitive data becomes more difficult to manage and you would have to write your own authentication/authorization logic in your Next.js SSR pages/endpoints.

Firebase as a platform is optimized for client-side auth and data access controls. Firestore libraries are built specifically for client-side data fetching with access rules defined in Firestore Security Rules and integrating with Firebase Authentication.

By using SSR to fetch sensitive data, you end up having to do work the Firebase platform is already built to do for you.

SSR of only public data with Firestore client-side fetching is the best of both worlds IMO.

This is just one opinion, SSR of secure content is certainly possible and has been done millions of times on the web, whether or not the complexity is worth the risk or cost is another.

next-firebase-auth pretty clearly define restrictions in their docs. If that is not an issue for you, then go ahead and continue to use it. Lack of custom claims is a bummer as they're hugely helpful.

>I am having issues deploying my app to Firebase. It does not deploy the latest code up. I think it must be a configuration issue, but I'm wondering if you have experienced that before.

I would need the `firebase deploy` error to help you here.

>I added `predeploy` steps today because that seemed to fix my deployment issues temporarily, but they are back now for some reason.

I have found the `firebase.json` `predeploy` scripts to be a bit flaky, so prefer to keep everything in `package.json`.

>Also, I set `public` to `nextjs` instead of what you have in your example (public/). It doesn't seem to make a difference, can you confirm why?

The `nextjs/` dir contains the build output of the Next.js app which is used by the Cloud Function `server.js` to be able to handle requests and build your page properly.

`public/` contains your static files to be hosted on the CDN. It just so happens that Firebase and Next.js use the same directory, `public/`, for this purpose.

Some files in `nextjs/` can be hosted on your CDN, but they are not strictly all files meant for a CDN. I wouldn't advise pushing this to your CDN instead of `public/` as you then miss hosting your static assets properly.

See the Next.js docs - https://nextjs.org/docs/basic-features/static-file-serving

I have explored extracting the assets and static files/pages from the `nextjs/` dir and into the `public/` dir, but it proves a lot of work for little gain (it saves on 1 request to the Cloud Function per resource, so little gains). It may become necessary for larger, content-heavy apps, but I am unsure I want to invest the time to build this interop layer. Interestingly, [SvelteKit][3] has built this separation into their framework for adapters to convert the app to a hosting environment, my [svelte-firebase-adapter][4] does this for Firebase.

[1]: https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration
[2]: https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables
[3]: https://github.com/sveltejs/kit/
[4]: https://github.com/jthegedus/svelte-adapter-firebase

**Comment by jthegedus** [comment]
Closing for now. Please re-open if you have further questions :)
